services:
  typedblazor:
    image: typedblazor:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: final
    volumes:
      - ~/.aspnet/https:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mysupersecretpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/TypedBlazor.pfx
    ports:
      - "5001:5001"
      - "5000:5000"